apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    course: docker
    duration: 25hrs
    trainer:  shafi
spec:
  containers:
  - name: nginx
    image:  nginx
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: label-demo
#   labels:
#     environment: production
#     app: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80